all:
	latex vakthesis.ins

clean:
	rm -f casus.sty speciality.* vakaref.cls vakthesis.cls *.log xampl-aref.tex xampl-bib.tex xampl-ch1.tex xampl-concl.tex xampl-intro.tex xampl-mybib.bib xampl-thesis.bib xampl-thesis.tex *~
